name: Run tests on AWS

on:
  pull_request:
  push:
    branches:
      - main

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: temurin
  AWS_REGION: eu-north-1
  WORKFLOW_ROLE_ARN: arn:aws:iam::653932013369:role/java-wonderland-github-actions-workflow-role
  RUNNER_ROLE_NAME: java-wonderland-github-actions-runner-role
  AMI_ID: ami-099451d897f38cebe
  EC2_INSTANCE_TYPE: c5.2xlarge
  SUBNET_ID: subnet-3914dd42
  SECURITY_GROUP_ID: sg-09ab440252230df2a

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/github-script@v7
        id: variables
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
        with:
          result-encoding: string
          script: |
            const runAttempt = process.env.RUN_ATTEMPT
            const fullSha = process.env.COMMIT_SHA
            const sha = fullSha.substring(0,7)
            const prefix = `gha-outputs/commit-${sha}/attempt-${runAttempt}`
            console.log(`Hello ${prefix}`)
            core.info(`S3_PREFIX=${prefix}`)
            core.exportVariable('S3_PREFIX', prefix);
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: maven
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
      - name: Upload JMH benchmarks jar
        uses: actions/upload-artifact@v4
        with:
          name: jmh-benchmarks
          path: jmh-benchmarks/target/jmh-benchmarks.jar
          retention-days: 7
          if-no-files-found: error
      - name: Upload JCStress runner jar
        uses: actions/upload-artifact@v4
        with:
          name: stress-tests
          path: stress-tests/target/stress-tests.jar
          retention-days: 7
          if-no-files-found: error
      - name: Upload test wrapper jar
        uses: actions/upload-artifact@v4
        with:
          name: test-wrapper
          path: test-wrapper/target/test-wrapper.jar
          retention-days: 7
          if-no-files-found: error

  start-runner-1:
    name: Start EC2 runner 1
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.WORKFLOW_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GHA_EC2_PAT }}
          ec2-image-id: ${{ env.AMI_ID }}
          ec2-instance-type: ${{ env.EC2_INSTANCE_TYPE }}
          subnet-id: ${{ env.SUBNET_ID }}
          security-group-id: ${{ env.SECURITY_GROUP_ID }}
          iam-role-name: ${{ env.RUNNER_ROLE_NAME }}
          aws-resource-tags: > 
            [
              {"Key": "project", "Value": "java-wonderland"},
              {"Key": "run_id", "Value": "${{ github.run_id }}" },
              {"Key": "runner", "Value": "runner-1"}
            ]
  run-jmh:
    name: Run JMH tests
    needs:
     - start-runner-1
    runs-on: ${{ needs.start-runner-1.outputs.label }} # run the job on the newly created runner
    steps:
      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Download Test wrapper
        uses: actions/download-artifact@v4
        with:
          name: test-wrapper
      - name: Download JMH runner jar
        uses: actions/download-artifact@v4
        with:
          name: jmh-benchmarks
      - name: Run JMH benchmarks
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
        run: java -jar test-wrapper.jar jmh -f 1

  stop-runner-1:
    name: Stop EC2 runner 1
    needs:
      - start-runner-1
      - run-jmh
    if: always()
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.WORKFLOW_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GHA_EC2_PAT }}
          label: ${{ needs.start-runner-1.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-1.outputs.ec2-instance-id }}

  start-runner-2:
    name: Start EC2 runner 2
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.WORKFLOW_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GHA_EC2_PAT }}
          ec2-image-id: ${{ env.AMI_ID }}
          ec2-instance-type: ${{ env.EC2_INSTANCE_TYPE }}
          subnet-id: ${{ env.SUBNET_ID }}
          security-group-id: ${{ env.SECURITY_GROUP_ID }}
          iam-role-name: ${{ env.RUNNER_ROLE_NAME }}
          aws-resource-tags: >
            [
              {"Key": "project", "Value": "java-wonderland"},
              {"Key": "run_id", "Value": "${{ github.run_id }}" },
              {"Key": "runner", "Value": "runner-2"}
            ]
  run-jmh-with-async:
    name: Run JMH tests with async prof
    needs:
     - start-runner-2
    runs-on: ${{ needs.start-runner-2.outputs.label }} # run the job on the newly created runner
    steps:
      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Download Test wrapper
        uses: actions/download-artifact@v4
        with:
          name: test-wrapper
      - name: Download JMH runner jar
        uses: actions/download-artifact@v4
        with:
          name: jmh-benchmarks
      - name: Run JMH benchmarks
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
        run: java -jar test-wrapper.jar jmh-with-async -f 1 -jvmArgs "-XX:+UnlockDiagnosticVMOptions -Xlog:class+load=info -XX:+LogCompilation" --async-path /home/ec2-user/async-profiler-2.9-linux-x64/build/libasyncProfiler.so
  stop-runner-2:
    name: Stop EC2 runner 2
    needs:
      - start-runner-2
      - run-jmh-with-async
    if: always()
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.WORKFLOW_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GHA_EC2_PAT }}
          label: ${{ needs.start-runner-2.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-2.outputs.ec2-instance-id }}

  start-runner-3:
    name: Start EC2 runner 3
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.WORKFLOW_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GHA_EC2_PAT }}
          ec2-image-id: ${{ env.AMI_ID }}
          ec2-instance-type: ${{ env.EC2_INSTANCE_TYPE }}
          subnet-id: ${{ env.SUBNET_ID }}
          security-group-id: ${{ env.SECURITY_GROUP_ID }}
          iam-role-name: ${{ env.RUNNER_ROLE_NAME }}
          aws-resource-tags: >
            [
              {"Key": "project", "Value": "java-wonderland"},
              {"Key": "run_id", "Value": "${{ github.run_id }}" },
              {"Key": "runner", "Value": "runner-3"}
            ]
  run-jcstress:
    name: Run JCStress tests
    needs:
     - start-runner-3
    runs-on: ${{ needs.start-runner-3.outputs.label }} # run the job on the newly created runner
    steps:
      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Download Test wrapper
        uses: actions/download-artifact@v4
        with:
          name: test-wrapper
      - name: Download JCStress runner jar
        uses: actions/download-artifact@v4
        with:
          name: stress-tests
      - name: Run JCStress tests
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
        run: java -jar test-wrapper.jar jcstress --no-split-compilation-modes

  stop-runner-3:
    name: Stop EC2 runner 3
    needs:
      - start-runner-3
      - run-jcstress
    if: always()
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.WORKFLOW_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GHA_EC2_PAT }}
          label: ${{ needs.start-runner-3.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-3.outputs.ec2-instance-id }}
