name: Run tests on AWS

on:
  pull_request:

env:
  REGION: eu-north-1
  WORKFLOW_ROLE_ARN: arn:aws:iam::653932013369:role/java-wonderland-github-actions-workflow-role
  RUNNER_ROLE_NAME: java-wonderland-github-actions-runner-role
  AMI_ID: ami-099451d897f38cebe
  EC2_INSTANCE_TYPE: t3.micro
  SUBNET_ID: subnet-3914dd42
  SECURITY_GROUP_ID: sg-09ab440252230df2a

jobs:
  build:
    name: Build project and run unit tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
      - name: Upload JMH runner jar
        uses: actions/upload-artifact@v3
        with:
          name: jmh-runner
          path: jmh-benchmarks/target/jmh-benchmarks.jar
          retention-days: 7
          if-no-files-found: error

  start-runner-1:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: $WORKFLOW_ROLE_ARN
          aws-region: $REGION

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GHA_EC2_PAT }}
          ec2-image-id: $AMI_ID
          ec2-instance-type: $EC2_INSTANCE_TYPE
          subnet-id: $SUBNET_ID
          security-group-id: $SECURITY_GROUP_ID
          iam-role-name: $RUNNER_ROLE_NAME

  do-the-job:
    name: Do the job on the runner
    needs:
     - start-runner-1
    runs-on: ${{ needs.start-runners.outputs.label }} # run the job on the newly created runner
    steps:
      - name: Download JMH runner
        uses: actions/download-artifact@v3
        with:
          name: jmh-runner
      - name: Display structure of downloaded files
        run: ls -R
      - name: Copy files to the test bucket with the AWS CLI
        run: |
          aws s3 cp jmh-benchmarks.jar s3://java-wonderland

  stop-runner-1:
    needs:
      - start-runner-1
      - do-the-job
    if: always()
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: $WORKFLOW_ROLE_ARN
          aws-region: $REGION
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GHA_EC2_PAT }}
          label: ${{ needs.start-runner-1.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-1.outputs.ec2-instance-id }}
