name: Run tests on AWS

on:
  pull_request:

jobs:
#  build:
#    name: Run anything on AWS
#    runs-on: ubuntu-latest
#    permissions:
#      id-token: write
#      contents: read
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v3
#      - name: Set up JDK 20
#        uses: actions/setup-java@v3
#        with:
#          java-version: '20'
#          distribution: 'temurin'
#          cache: maven
#      - name: Build with Maven
#        run: mvn -B verify --file pom.xml

  start-runners:
#    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::653932013369:role/java-wonderland-github-access-role
          aws-region: eu-north-1

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GHA_EC2_PAT }}
          ec2-image-id: ami-099451d897f38cebe
          ec2-instance-type: t3.nano
          subnet-id: subnet-3914dd42
          security-group-id: sg-09ab440252230df2a
      - name: print runner details
        run: |
          echo "Runner label: >> ${{ steps.start-ec2-runner.outputs.label }} <<"
          echo "Runner EC2 instance id: >> ${{ steps.start-ec2-runner.outputs.ec2-instance-id }} <<"

  do-the-job:
    name: Do the job on the runner
    needs:
     - start-runners
    runs-on: ${{ needs.start-runners.outputs.label }} # run the job on the newly created runner
    steps:
      - name: create test file
        run: |
          echo "hello world" >> hello.txt
      - name: Copy files to the test bucket with the AWS CLI
        run: |
          ls
          aws s3 cp hello.txt s3://java-wonderland

  stop-runners:
    needs:
      - start-runners
      - do-the-job

    if: always()

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::653932013369:role/java-wonderland-github-access-role
          aws-region: eu-north-1
      - name: print runner details
        run: |
          echo "Runner label: >> ${{ needs.start-runners.outputs.label }} <<"
          echo "Runner EC2 instance id: >> ${{ needs.start-runners.outputs.ec2-instance-id }} <<"
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GHA_EC2_PAT }}
          label: ${{ needs.start-runners.outputs.label }}
          ec2-instance-id: ${{ needs.start-runners.outputs.ec2-instance-id }}
